### ISSUE TITLE
Missing an "import torch" 

### ISSUE THREAD

**Issue by gaetan-landreau** [NVlabs/UMR#1]
There is a missing import  ( import torch before the from torch.utils.cpp_extension) at the begging of a setup.py file for the neural mesh renderer external library.

**Comment by sunshineatnoon** [comment]
Hi, the neural mesh renderer is cloned from this repo: [https://github.com/daniilidis-group/neural_renderer](https://github.com/daniilidis-group/neural_renderer). So I believe that issue is related with it, not this repo.
