### ISSUE TITLE
About template updating

### ISSUE THREAD

**Issue by layumi** [NVlabs/UMR#15]
Hi @sunshineatnoon Xueting, 
Thanks a lot for the great work. 
I am not sure whether I am right on understanding the code.

- `train_s1.py` is to update the template with all data in the dataset every 5 epochs, but do not deal with the case of `the direction of the horse head`. 

- `avg_uv.py` is to select the most frequent horse template (as described in the paper appendix `select the horse head on the left and ensure large IoU with ground-truth mask`).

- `train_s2.py` removes the horse template updating `mean_v` in `train_s1.py` and focuses on updating the camera parameter / shape biases.

**Comment by sunshineatnoon** [comment]
> Hi @sunshineatnoon Xueting, Thanks a lot for the great work. I am not sure whether I am right on understanding the code.
> 
>     * `train_s1.py` is to update the template with all data in the dataset every 5 epochs, but do not deal with the case of `the direction of the horse head`.
> 
>     * `avg_uv.py` is to select the most frequent horse template (as described in the paper appendix `select the horse head on the left and ensure large IoU with ground-truth mask`).
> 
>     * `train_s2.py` removes the horse template updating `mean_v` in `train_s1.py` and focuses on updating the camera parameter / shape biases.

Yes. That's correct!
