### ISSUE TITLE
mean_v.pth file not found while training train_s2.py

### ISSUE THREAD

**Issue by aarti-b** [NVlabs/UMR#4]
I have trained from scratch as mentioned in Readme.md.
`python -m UMR.experiments.train_s1 --name=cub_s1 --gpu_num 4 --multi_gpu -cub_dir CUB_200_2011/ --cub_cache_dir UMR/cachedir/cub
`
and then for semantic template I ran :
`python -m UMR.experiments.avg_uv --model_path UMR/cachedir/snapshots/cub_s1/pred_net_latest.pth --batch_size 16 --out_dir UMR/cachedir/snapshots/cub_s1 --cub_dir CUB_200_2011/ --cub_cache_dir UMR/cachedir/cub --scops_path SCOPS/results/cub/ITER_60000/train/dcrf_prob/
`
now when I run final training using train_s2 file I get above error. Any suggestion would be helpful. Thank you.

**Comment by sunshineatnoon** [comment]
Hi, I updated the `avg_uv.py` file by adding [this line](https://github.com/NVlabs/UMR/blob/master/experiments/avg_uv.py#L305). Could you please try if it works now? Meanwhile, you can use the template [here](https://drive.google.com/file/d/1lwZu6Rl8iL9KZBLvK4dIneB_dKMtC9uY/view?usp=sharing) to train `train_s2.py` too.

**Comment by aarti-b** [comment]
Hi, Thank you for your response. I ran `avg_uv.py` by adding line you mentioned. It works. But running `train_s2.py` is causing this error `RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED` . 
Although this `mean_v.pth` issue is resolved. And Thank you for sharing templates and pre-trained net.

**Comment by sunshineatnoon** [comment]
> Hi, Thank you for your response. I ran `avg_uv.py` by adding line you mentioned. It works. But running `train_s2.py` is causing this error `RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED` .
> Although this `mean_v.pth` issue is resolved. And Thank you for sharing templates and pre-trained net.

Hi, could give more information of the error? For instance, which line causes the error? Could you paste more error information from your terminal? Thanks

**Comment by aarti-b** [comment]
yeah sure this is traceback : 
`Traceback (most recent call last):
  File "lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/UMR/experiments/train_s2.py", line 483, in <module>
    app.run(main)
  File "lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "UMR/experiments/train_s2.py", line 479, in main
    trainer.init_training()
  File "UMR/nnutils/train_utils.py", line 177, in init_training
    self.define_criterion()
  File "UMR/experiments/train_s2.py", line 161, in define_criterion
    batch_size = int(opts.batch_size/opts.gpu_num))
  File "UMR/nnutils/loss_utils.py", line 345, in __init__
    tex = torch.nn.functional.grid_sample(uv_img, uv_sampler)
  File "lib/python3.6/site-packages/torch/nn/functional.py", line 2717, in grid_sample
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED`

Couple of things I tried to resolve it are: 
1. Changed CUDA version to 10.0 
2. Installed new pytorch version 1.7.1 (but then it gave some issue in render module so i installed back the version you specified in requirements.txt)
none of them worked.

**Comment by sunshineatnoon** [comment]
Thanks. How many GPUs are you using and what's the training command did you use?

**Comment by aarti-b** [comment]
I am using 1 GPU and  
`python -m UMR.experiments.train_s2 --name=cub_s2 --batch_size 16 --cub_dir UMR/CUB_200_2011/ --cub_cache_dir UMR/cachedir/cub --scops_path UMR/SCOPS/results/cub/ITER_60000/train/dcrf_prob/ --stemp_path UMR/cachedir/snapshots/cub_s1`
paths are correctly pointing.

**Comment by aarti-b** [comment]
Also just to mention, I tried batch_size 8, 4 and 2 as well to check if GPU memory is issue.. It gave same error.. and used same GPU for training `train_s1.py` with batch_size 64, it worked well. So GPU memory issue can be ruled out.

**Comment by sunshineatnoon** [comment]
Hi, I tried to reproduce the error but I didn't see it. It looks like the error is caused by [this line](https://github.com/NVlabs/UMR/blob/master/nnutils/loss_utils.py#L345). Could you add these two lines:
```
torch.save(uv_img, 'uv_img.pth')
torch.save(uv_sampler, 'uv_sampler.pth')
```
 before [this line](https://github.com/NVlabs/UMR/blob/master/nnutils/loss_utils.py#L345) and send me the `uv_img.pth` and `uv_sampler.pth` files? I suspect there're some invalid values in these two files. 

Or you could try to use the semantic template I provided above by using `--stemp_path UMR/cachedir/cub/scops/` and see if it runs.

**Comment by aarti-b** [comment]
Hi, I tried with semantic template you provided but I got same error. I save `.pth` file as you mentioned. I have put them here [uv_[].pth](https://drive.google.com/drive/folders/12Ogr_p8awSXS0Z_m2NCQhIP0VdEY3n4w).
I saved them with semantic templates you provided.

**Comment by sunshineatnoon** [comment]
Thanks. I tried the `grid_sample` function with the files you provided and it runs fine as below
<img width="780" alt="Screen Shot 2020-12-23 at 11 02 28 AM" src="https://user-images.githubusercontent.com/7546747/103029347-79c8e600-450e-11eb-91ea-bd21604ed01c.png">

Could you also see if you can call `grid_sample()` function as well? If you can't, then I think there's something wrong with the Cuda environment on your machine.
