### ISSUE TITLE
Fail to run the demo

### ISSUE THREAD

**Issue by njfugit** [NVlabs/UMR#8]
Hi xueting,
When I input
**python -m UMR.experiments.demo --model_path UMR/cachedir/snapshots/cub_net/pred_net_latest.pth --img_path UMR/demo_imgs/birdie.jpg --out_path UMR/cachedir/demo**
I put the specific error report in the attached screenshot

![Screenshot from 2021-03-26 20-48-27](https://user-images.githubusercontent.com/28702691/112709998-ea5e1500-8ef8-11eb-8465-a2b3ddc2341f.png)
What's wrong ?

**Comment by yyyyy525** [comment]
Hi, I got the same problem too! Have you solved this problem yet?
